name = "ComputerGroups"
uuid = "16364e1d-fec4-4fac-b840-ca2ded382750"
authors = ["Aiden Rohrbach <arohrbachj@protonmail.com>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"

[compat]
Combinatorics = "1.0.3"
Primes = "0.5.7"
